spring:
  jpa:
    show-sql: true
    generate-ddl: true
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/pformlicense
    defaultSchema: public
    username: license
    password: password
    driver-class-name: org.postgresql.Driver
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
#  hbm2ddl.auto: create